version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14  # Use the desired Node.js version
        ports:
          - 22:22  # Expose port 22 on the container
    steps:
      - checkout  # Pull down the code from the repository
      - run:
          name: Install Dependencies
          command: |
            npm install
            mkdir /tmp/artifacts;

      - store_artifacts:
          path: /tmp/artifacts

      - add_ssh_keys:
          fingerprints:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdK5x2L5s7nguzSrQODCjDJpAAYnE1pswxfRkmB0rqxxgQMm7GMbYUF54w/bJL1/S1P0J/c4LOrpKQjNGDn9BxvCciR7OOMYFeGjxqA+/JN2uXgbYgk9cxZrLvcS2q+JC5hxsh7tCpxwvQOCEOLzOF6Ge0J9RygyW4ir8fG5ZeCSU3KVuYnpsScc/eDaCRobpPcxY2C/XTMxVMa9fJfg5tQgd6nafpESDaAxrA+8sIU88GXxI76B5pcrKx1wAqpzeO5+HuWsIHoa6Cf/27qfSqlujJ/gP7gpE7cf58+Pb4/5RUSwSQIPaEcp2cxpMBhqiWLLkbqAWxEQc45aR0ThixpzP0xQdbeDu7KptcPYPkgN6x/ZIVHMDFxpWjvs3VaTEww5CPPNN01pomadS5kq2KSIrDS9Nzzs7v0O1+AfwTukXfjPcq260kSZocWPRV78OQH7YGH/gBDGoOE2rPIvjhyiHhz+6JLErUzM9VQr7J5eDhZ3BRvt63gciywp41iVE= admin@admins-MacBook-Pro.local"

      - run:
          name: Deploy via SSH
          command: |
            ssh -o StrictHostKeyChecking=no -p 22 admin@192.168.1.45 "mkdir -p /Users/admin/projects/deploy && cd /Users/admin/projects/deploy && git clone <YOUR_GIT_REPO_URL> . && git pull origin main && npm install && npm start"
