version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14  # Use the desired Node.js version
    steps:
      - checkout  # Pull down the code from the repository
      - run:
          name: Install Dependencies
          command: npm install
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

